version = 1

[[annotations]]
path = [
    "Sources/SpeziLicense/SpeziLicense.docc/Resources/**"
]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"
